base_app/urls.py
from django.urls import path
from base_app import views

app_name = 'base_app'

urlpatterns =[
path('',views.index, name = "index"),
path('home/',views.index, name = "tab1"),
path('register/',views.register, name = "register"),
path('login/',views.user_login, name = "login"),
path('logout/',views.user_logout, name = "logout"),
path('delivery_agents/',views.delivery_agents, name = "delivery_agents"),
path('orders_list/',views.orders_list, name = "orders_list"),
path('customer_list/',views.customer_list, name = "customer_list"),
path('order_create/',views.order_create, name = "order_create"),
path('get_da_details/',views.get_da_details, name = "get_da_details"),
path('change_user_status/',views.change_user_status, name = "change_user_status"),

]

ideliver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.
# from base_app import urls as base_app_urls
from base_app import views as base_app_views
# python -c "import django; print(django.get_version())"
urlpatterns = [
    # path('base_app/', base_app_urls),
    # path('', base_app_views.index1),
    path('',include('base_app.urls')),
    # path('base_app/',include('base_app.urls')),
    path('admin/', admin.site.urls),
    # url(r'^$', base_app_views.index, name='index'),
    # url(r'^base_app/',include('base_app.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileInfo, Order, OrderItem, DaProfile
from base_app import dbconstants


class UserParentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        # exclude = ['username']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        exclude = ['username']

class UserFormDa(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'first_name', 'email', 'password')



class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('phone_primary', 'phone_secondary', 'location_area','location_sublocality','location_locality','location_city','location_pincode','profile_pic')


class UserProfileInfoFormDa(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('phone_primary', 'phone_secondary', 'location_area','location_sublocality','location_locality','location_city','location_pincode', 'profile_pic')

    def __init__(self, *args, **kwargs):
        super(UserProfileInfoFormDa, self).__init__(*args, **kwargs)
        self.fields['location_locality'].required = False
        self.fields['phone_secondary'].required = False

class DaProfileForm(forms.ModelForm):
    class Meta():
        model = DaProfile
        fields = ('user', 'driving_liscence_pic', 'pan_card_pic','rc_pic')

    def __init__(self, *args, **kwargs):
        super(DaProfileForm, self).__init__(*args, **kwargs)
        self.fields['user'].required = False
        self.fields['pan_card_pic'].required = False
        self.fields['rc_pic'].required = False

class OrderForm(forms.Form):
    # class Meta():
    #     model = Order
    #     fields = ('user_delivery_agent', 'delivery_charges', 'status_note')

    customer_name = forms.CharField(label='Customer Name', max_length=50)
    phone_primary = forms.CharField(max_length=10, label='Phone Number' )
    location_sublocality = forms.CharField(max_length=80, label='Address' )
    location_locality = forms.CharField(max_length=80, label='Locality')
    location_city = forms.CharField(max_length=80,  label='City')
    # location_state = models.CharField(max_length=80, unique=False, default="KERALA")
    location_pincode = forms.CharField(max_length=6, label='Pincode')
    delivery_agent = forms.ModelChoiceField(queryset=UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT))
    # UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT)
    # forms.ModelChoiceField(queryset=User.objects.all().order_by('username'))
    # forms.CharField(max_length=80,  label='Delivery Agent')



class OrderItemForm(forms.ModelForm):

    class Meta():
        model = OrderItem
        fields = ('measurement_unit', 'item_name', 'item_quantity')
        exclude = ['measurement_unit']

base_app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from base_app.forms import UserProfileInfoForm, UserForm, UserFormDa, OrderForm, UserParentForm, UserProfileInfoFormDa, OrderItemForm, DaProfileForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
import datetime
from base_app.utils import random_string_generator
import string
from base_app import constants, dbconstants
# from django.db import models
from base_app.models import UserProfileInfo, Order, OrderItem, ItemMeasuementUnit, DaProfile
from django.core import serializers
# Create your views here.
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
import json
from base_app import smsbase
import re
# from itertools import izip


def change_user_status(request):

    print("came changestat")
    username = request.POST['username']
    user_status = request.POST['user_status']

    user_obj = User.objects.get(username=username)
    user_profile = UserProfileInfo.objects.get(user=user_obj)

    # user_profile = UserProfileInfo.objects.get(username=username)

    if user_status == "AT":
        print("useractive")
        user_status = dbconstants.USER_STATUS_DISABLED
    else:
        user_status = dbconstants.USER_STATUS_ACTIVE
        print("userinactive")
    user_profile.user_status = user_status
    user_profile.save()

    return HttpResponse(json.dumps({"SUCCESS":True, "RESPONSE_MESSAGE":"Status updated"}),
    content_type="application/json")





def customer_list(request):

    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_CONSUMER).order_by('-created_at')
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        # pic = user_temp.profile_pic
        # print(pic)
        user_parent_set = {}
        # user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)

    serialized_obj = serializers.serialize('json', user_list)

    print("sizeb:"+ str(user_list.count()))


    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 9)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'base_app/customers.html',  {'state_list':dbconstants.STATE_LIST_DICT, 'users': users})


def index(request):

    # smsbase.sendOrderCreationMessage()

    order_count = Order.objects.all().count()
    order_delivered_count = 0
    delivery_boy_count = UserProfileInfo.objects.filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT).count()

    customers_count  = UserProfileInfo.objects.filter(user_type = dbconstants.USER_TYPE_CONSUMER).count()

    # delivery_boy_count = 0

    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT)
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        pic = user_temp.profile_pic
        print(pic)
        user_parent_set = {}
        user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)
        # serialized_obja = serializers.serialize('json', [user_parent_set])
        # # # filter(user__username ='azr')
        # # # user_list = User.objects.filter(username ='azr')
        # dataa = {"aSomeModel_json": serialized_obj}
        # ("atitaa")
        # print(dataa)
        #
        #

    serialized_obj = serializers.serialize('json', user_list)



    # profile_check = UserProfileInfo.objects.filter(phone_primary=post_data["phone_primary"], user_type = dbconstants.USER_TYPE_CONSUMER)

    # Order.objects.prefetch_related('user_customer').prefetch_related('user_delivery_agent').all().order_by('-updated_at')




    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 100)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)


    today = datetime.date.today()

    base_dict = {"order_count":order_count, "delivery_boy_count":delivery_boy_count, "order_delivered":order_delivered_count, "customers_count":customers_count, "delivery_agents":users, 'pic_server_prefix':'http://127.0.0.1:8000/media/' }
    return render(request, 'base_app/index.html', context = base_dict)

@login_required
def delivery_agents(request):
    # user_profile_list = UserProfileInfo.objects.filter(user_type =dbconstants.DELIVERY_AGENT)
    # user_list = User.objects.filter(user_profile_info__user_type = dbconstants.DELIVERY_AGENT)
    # user_list = UserProfileInfo.objects.all().select_related('user')
    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT).order_by('-updated_at')
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        pic = user_temp.profile_pic
        print(pic)
        user_parent_set = {}
        user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)
        # serialized_obja = serializers.serialize('json', [user_parent_set])
        # # # filter(user__username ='azr')
        # # # user_list = User.objects.filter(username ='azr')
        # dataa = {"aSomeModel_json": serialized_obj}
        # ("atitaa")
        # print(dataa)
        #
        #

    serialized_obj = serializers.serialize('json', user_list)
    # filter(user__username ='azr')
    # user_list = User.objects.filter(username ='azr')
    # dataa = {"SomeModel_json": serialized_obj}
    # print("titaa")
    # print(dataa)
    # print("sizea:"+ str(user_profile_list.count()))
    print("sizeb:"+ str(user_list.count()))


    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 9)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'base_app/delivery_agents.html',  {'state_list':dbconstants.STATE_LIST_DICT, 'users': users, 'pic_server_prefix':'http://127.0.0.1:8000/media/' })

@login_required
def orders_list(request):

    order_list = Order.objects.prefetch_related('user_customer').prefetch_related('user_delivery_agent').all().order_by('-updated_at')

    order_list_final = []

    for order_temp in order_list:
        # print("caddd")
        # print("cadddw"+str(order_temp.user_customer))
        user_customer_m =User.objects.get(username = order_temp.user_customer)
        user_customer = UserProfileInfo.objects.get(user = user_customer_m)

        user_delivery_agent_m =User.objects.get(username = order_temp.user_delivery_agent)
        user_delivery_agent = UserProfileInfo.objects.get(user=user_delivery_agent_m)

        user_customer.user_location_display = user_customer.location_area +','+user_customer.location_sublocality+","+user_customer.location_city+","+user_customer.location_pincode


        # getting order item

        order_items = OrderItem.objects.filter(order = order_temp)
        # print("sizeaaa:"+ str(order_items.count()))

        item_name =""

        for order_item in order_items:
            if item_name != '':
                item_name += ", "+order_item.item_name
            else:
                item_name += order_item.item_name

        order_temp.order_items = item_name

        # getting status text
        order_temp.status = dbconstants.ORDER_STATUS_DIC[order_temp.status]



        # print(user_meta_raw.username)
        order_foreign = {}
        order_foreign['user_customer'] = user_customer
        order_foreign['user_delivery_agent'] = user_delivery_agent

        #
        #

templates/base_app/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>I Delivery Services | CRM</title>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:500,700&display=swap" rel="stylesheet">
  <script src="../static/js/jquery-3.4.1.js"></script>
  <link rel="stylesheet" href="../static/css/main.css">
  <!-- <script src="http://code.jquery.com/jquery-3.4.1.min.js"></script> -->
  <script src="{% static "js/delivery_agents.js" %}" > </script>
</head>
<body>
  <div class="row">
  <div class="col-12 left_sidebar col-md-2">
    <div class="logo"><img src="../static/images/logo.svg" alt=""></div>
    <ul class="sidebar-nav">
      <li role="presentation"><a href="{% url 'base_app:index' %}"> <span class="icon_set icon-home menu_icon"></span> Home </a></li>

      {% if user.is_authenticated %}
      <li role="presentation"><a  href="{% url 'base_app:delivery_agents' %}"> <span class="icon_set icon-avatar menu_icon"></span> Delivery Agents</a></li>
      <li role="presentation"><a  href="{% url 'base_app:orders_list' %}"> <span class="icon_set icon-package menu_icon"></span> Orders</a></li>
      <li role="presentation"><a  href="{% url 'base_app:customer_list' %}"> <span class="icon_set icon-group menu_icon"></span> Customer</a></li>
      <li role="presentation"><a  href="{% url 'base_app:orders_list' %}"> <span class="icon_set icon-settings menu_icon"></span> Roles</a></li>
      {% else %}
      <li role="presentation" ><a  href="{% url 'base_app:login' %}">Login</a></li>
      {% endif %}

    </ul>
  </div>

  <div class="col-12 col-md-10 no-padding">
    <div class="top_header">
        <div class="col-md-10 float-left"></div>
        <div class="col-md-2 float-right">
            {% if user.is_authenticated %}
            <a  class="text-right w-100 float-right" href="{% url 'base_app:logout' %}">{{ user.username }} ( Logout ) </a>
            {% else %}
            <a  href="{% url 'base_app:login' %}">Login</a>
            {% endif %}
        </div>
      </div>
    <div class="right_sidebar">

    {% block body_block %}
    {% endblock %}

    </div>
  </div>
</div>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_app/customers.html
{% extends "base_app/base.html" %}
{% block body_block %}

<input type="hidden" id="ul_user_status" value="{% url 'base_app:change_user_status' %}" />
<div class="float-left col-md-12 no-padding">
  <div class="col-12 col-md-4 float-left pl_0">
    <h1 class="header_title float-left mt_15 mb_15">Customers </h1>
  </div>
  <div class="col-md-8 float-right pr_0 mb_15">
    <input type="email" class="form-control float-left col-md-8 mt_15" placeholder="Search here..">
  </div>
<div class="common_container pt_0">
  <div class="table-responsive">
      <table class="table">
          <thead>
            <tr>
              <th>Customer Name</th>
              <th>Mobile</th>
              <th>Address</th>
              <th>Pincode</th>
              <th>City</th>
              <th>Created On</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr>

                <td>{{ user.user_meta.username }}</td>
                <td>{{ user.user_profile.phone_primary }}</td>
                <td>{{ user.user_profile.location_area }}, {{ user.user_profile.location_sublocality }} </td>
                <td>{{ user.user_profile.location_pincode }}</td>
                <td>{{ user.user_profile.location_city }}</td>
                <td>{{ user.user_profile.created_at }}</td>

                <td>
                  {% if user.user_profile.user_status == "AT" %}

                  <label class="switch">
                  <input type="checkbox" checked onclick="deActivateUser('{{ user.user_meta.username }}')" >
                  <span class="slider"></span>
                  </label>

                  {% else %}

                  <label class="switch">
                  <input type="checkbox"  onclick="activateUser('{{ user.user_meta.username }}')" >
                  <span class="slider"></span>
                  </label>

                  {% endif %}

                </td>

              </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
</div>

{% if users.has_other_pages %}
<div class="col-md-12 float-left pr_0">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if users.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ users.previous_page_number }}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      {% for i in users.paginator.page_range %}
      {% if users.number == i %}
      <li class="page-item active"><a class="page-link" href="#"><span>{{ i }}</span></a> </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if users.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ users.next_page_number }}">Next </a></li>
      {% else %}
      <!-- <li class="disabled"><span>&raquo;</span></li> -->
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
<!-- <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li> -->

{% endif %}

{% endblock %}

templates/base_app/hello.html
hello

templates/base_app/index.html
{% extends "base_app/base.html" %}
{% block body_block %}



  <div class="col-md-12 col-lg-12 float-left col-12 no-padding mt_20">
    <div class="col-md-3 float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_1">
        <span class="icon_set icon-package doashbord_icon"></span>
        <span class="doashbord_big_text">{{order_count}}</span>
        <h1 class="primary_title w-100">TOTAL ORDER</h1>

      </div>
    </div>
    <div class="col-md-3 float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_2">
        <span class="icon_set icon-delivery-truck doashbord_icon"></span>
        <span class="doashbord_big_text">{{order_delivered}}</span>
        <h1 class="primary_title w-100">ORDER DELIVERED</h1>

      </div>
    </div>
    <div class="col-md-3 float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_3">
        <span class="icon_set icon-group doashbord_icon"></span>
        <span class="doashbord_big_text">{{customers_count}}</span>
        <h1 class="primary_title w-100">CUSTOMERS</h1>

      </div>
    </div>
    <div class="col-md-3 float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_4">
        <span class="icon_set icon-avatar doashbord_icon"></span>
        <span class="doashbord_big_text">{{delivery_boy_count}}</span>
        <h1 class="primary_title w-100">DELIVERY BOY</h1>

      </div>
    </div>
  </div>
<div class="col-md-6 col-12 col-lg-6 float-left pt_30 pl_0">

  <div class="common_container p_15">
    <h1 class="header_title w-100 mt_10">Delivery Boy</h1>
    <ul class="worker_list pt_15">


<!-- delivery_agents -->

{% for user in delivery_agents %}

<li>
  <div class="workers_box">
      {% if user.user_profile.profile_pic %}
    <img src="{{ user.user_profile.profile_pic.url }}" >
    {% else %}
    <img src="" >
    {% endif %}
    <div class="workers_caption">
      <span class="workers_name">{{ user.user_meta.username }}</span>
      <span class="workers_location">
        {{ user.user_profile.location_area }} ,
        {{ user.user_profile.location_sublocality }}
      </span>
  </div>
  </div>
</li> <!--========== END of LI Tags =========-->
{% endfor %}


    </ul>
  </div>
</div>

{% endblock %}

templates/base_app/index1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title> static tests</title>
  <link rel="stylesheet" href="{% static "css/base_style.css" %} ">
</head>
<body>
<!-- <script src= src="{% static "js/delivery_agents.js" %}" > </script> -->
<h1>{{test_var}}</h1>
<p>This is another paragraph.</p>
<img src="{% static "images/angrybat.jpg" %}" alt="Not loaded" >
</body>
</html>

templates/base_app/login.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>I Delivery Services | CRM</title>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:500,700&display=swap" rel="stylesheet">
  <script src="../static/js/jquery-3.4.1.js"></script>
  <link rel="stylesheet" href="../static/css/main.css">


</head>
{% block body_block %}
<div class="login_contianer">
  <input type="hidden" id="login_success" value="{% url 'base_app:index' %}" />
  <div class="col-lg-2 col-md-2 float-left"></div>
  <div class="col-12 col-lg-8 col-md-8 float-left">
    <div class="login_box">
      <div class="col-md-7 float-left no-padding col-6">
        <div class="left_login">
            <ul class="pro_list">
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Home Need</span></li>
              <li><img src="/static/images/stationery.svg" alt=""><span class="pro_list_text">Stationery</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Personal Product</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Food</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Medicine</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Pet Product</span></li>
            </ul>

        </div>
      </div>
      <div class="col-md-5 float-left no-padding col-6">
        <div class="right_login">
            <img src="/static/images/logo.svg" alt="">
          <span class="font_14 second_color w-100 float-left mt_30">WELCOME BACK</span>
          <h1 class="header_title float-left mb_20 w-100">Login to your account</h1>
          <form id="login_form" action="{% url 'base_app:login' %}" method="post">

            {% csrf_token %}

            <div class="form-group col-12 col-md-12 float-left no-padding">
              <label for="exampleInputEmail1">User Name</label>
              <input type="text" name="username" id="username" class="form-control" placeholder="Enter email">
            </div>
            <div class="form-group col-12 col-md-12 float-left no-padding">
              <label for="exampleInputEmail1">Password</label>
              <input type="password" name="password" id="password" class="form-control" placeholder="Password">
            </div>
            <h1 id="error_el" class="header_title float-left mb_20 w-100"> </h1>
            <a onclick="proceedUserLogin()" name="" value="Login" class="btn primary_btn mt_10">login</a>

          </form>
        </div>
      </div> <!--Left END-->
    </div>

    </div>
  <div class="col-lg-2 col-md-2 float-left"></div>
</div>
<script src="{% static "js/delivery_agents.js" %}" > </script>

{% endblock %}

templates/base_app/order_create.html
{% extends "base_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">


  {% if registered %}
  <h1>Registerion successful!</h1>
  {% else %}
  <h1>Create Order</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{order_form.as_p}}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}

templates/base_app/registration.html
{% extends "base_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">


  {% if registered %}
  <h1>Registerion successful!</h1>
  {% else %}
  <h1>Delivery Agent Registation</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}